# Generated by Django 3.1.1 on 2020-10-06 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('distance', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_number', models.IntegerField()),
                ('elapsed_time', models.CharField(max_length=200)),
                ('moving_time', models.CharField(max_length=200)),
                ('avg_pace', models.CharField(max_length=200)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_runs.run')),
            ],
        ),
    ]
