# Generated by Django 3.1.1 on 2020-10-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_runs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='avg_pace',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='split',
            name='elapsed_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='split',
            name='moving_time',
            field=models.TimeField(),
        ),
    ]
