# Generated by Django 3.1.1 on 2022-01-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_runs', '0006_auto_20201017_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='split',
            name='avg_pace',
        ),
    ]
