# Generated by Django 3.1.1 on 2022-01-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_runs', '0007_remove_split_avg_pace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='elapsed_time',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='split',
            name='moving_time',
            field=models.FloatField(max_length=5),
        ),
    ]
